### ISSUE TITLE
Front - 권한 별로 접근 페이지 분리

### ISSUE THREAD

**Issue by Mizz1ove** [nhnacademy-aiot1-team3/roadmap#26]
1. 공통 기능

- [ ] 아이디 / 비밀번호 찾기 및 수정
- [ ] 회원가입 시 아이디 비밀번호 중복 확인
- [ ] 프로필 사진 등록
- [ ] 대시 보드에 원하는 차트 정렬 기능
  - [ ] 온도
  - [ ] 습도
  - [ ] co2
  - [ ] 전력
  - [ ] 도어 센서

2. Admin 페이지

- [ ] 모든 페이지 접근 가능
- [ ] Admin 관리 페이지
    - owner 회원 가입 요청 승인, 거절
    - 부서 추가 및 삭제 요청 승인, 거절
    - owner 회원 목록
 - [ ] 공지사항 추가 및 수정

3. Owner 페이지

- [ ] 마이페이지
  - [ ] 개인정보(id,pw, 프로필 이미지)
  - [ ] 비밀번호 변경
  - [ ] 부서 목록 및 추가/삭제 요청 기능
    - 각 부서별로 viewer 승인대기 목록 확인 기능
- [ ] 센서 배터리 현황 view
- [ ] Error log view
- [ ] Sensor 목록 view
- [ ] 대시보드 - 원하는 차트 선택 후 정렬
- [ ] 습도, co2, 전력
  - [ ] 여러 차트 중 선택 후 정렬 기능
  - [ ] sensor 추가 기능
  - [ ] sensor 목록 기능
- [ ] 온도
  - [ ] 여러 차트 중 선택 후 정렬 기능
  - [ ] ai 제어와 기본 제어 중 선택 기능
- [ ] 도어 센서 리스트
  - [ ] ai 제어와 기본 제어 중 선택 기능
  - [ ] 출입 로그 확인
  - [ ] 설정된 시간동안의 출입 빈도수 그래프
  - [ ] 도어 센서 설정 페이지
    - [ ] 원하는 시간 설정 및 삭제
  - [ ] 현재 구역별 인원 그래프

4. Viewer 페이지  

- [ ] 대시 보드에 원하는 차트 정렬 기능
  - [ ] 온도
  - [ ] 습도
  - [ ] co2
  - [ ] 전력
  - [ ] 도어 센서
- [ ] 내 정보
