### ISSUE TITLE
Eureka Server 구현 및 배포

### ISSUE THREAD

**Issue by SeinJs** [nhnacademy-aiot1-team3/roadmap#45]
- [x] Spring Security 적용
- [x] 각 API 서버들은 Server client이며 client가 직접 registry에 등록
- [x] client side discovery 적용
- [x] Test Code 완성
