### ISSUE TITLE
센서 재선정 및 데이터 구성 계획 (DELAYED)

### ISSUE THREAD

**Issue by SeinJs** [nhnacademy-aiot1-team3/roadmap#54]
- [x] 센서 종류 정하기
- [x] 센서 위치 정하기
- [x] 제어 방법 정하기
- [x] topic 틀, 가공된 센서 데이터 구조 틍 정하기
- [x] 통신 방법 및 어떤 구조의 데이터를 주고 받을 지
- [x] 실시간 데이터, 가공된 데이터 용도 정하기
