### ISSUE TITLE
Rule Engine - 결측치 필터링

### ISSUE THREAD

**Issue by SeinJs** [nhnacademy-aiot1-team3/roadmap#64]
- [ ] payload의 value값이 NaN 또는 Null과 같이 undefined 인지 확인
- [ ] 결측치에 해당하면 7번으로 이동
- [ ] 그 외에는 3번으로 이동
- [ ] 에러로그 테이블에 에러 타입 추가 할거? <--
