### ISSUE TITLE
Rule Engine - 오탐탐지 필터링

### ISSUE THREAD

**Issue by SeinJs** [nhnacademy-aiot1-team3/roadmap#65]
- [ ] payload의 value값이 오류에 해당하는 값인지 판별(ex. temperature value : 500)
- [ ] 오류로 판정 시 7번으로 이동
- [ ] 그 외에는 4번으로 이동
- [ ] 오탐 기준 정하기 <--
- [ ] (오류탐지 하는 방법 아직..) <--
- [ ] 에러로그 테이블에 에러 타입 추가 할거? <--
