### ISSUE TITLE
Rule Engine - 기능별 분류 설정

### ISSUE THREAD

**Issue by SeinJs** [nhnacademy-aiot1-team3/roadmap#66]
- [ ] 데이터베이스에서 센서의 설정된 기능(function_id)을 확인
- [ ] function_id별로 흐름 제어
  - [ ] function_id : 0 (read_only) -> 7번으로 이동
  - [ ] functoin_id : 1 (basic) -> 5번으로 이동
  - [ ] function_id : 2 (ai) -> 4-1번으로 이동
