### ISSUE TITLE
Rule Engine - AI 설정

### ISSUE THREAD

**Issue by SeinJs** [nhnacademy-aiot1-team3/roadmap#67]
- [ ] 센서 타입별 학습된 AI모델 사용
- [ ] 실시간 데이터를 AI모델에 적용
- [ ] 적용 후 결과를 5번으로 이동
