### ISSUE TITLE
Sensor Api - 가공된 데이터 조회

### ISSUE THREAD

**Issue by kkh5535** [nhnacademy-aiot1-team3/roadmap#72]
- [ ] Rule Engine에서 가공된 센서 데이터를 조회할 수 있어야 한다.
- [ ] 온도, 습도, CO2, 마그네틱 접점의 데이터를 조회할 수 있어야 한다.
- [ ] RDB에서 가져온 데이터를 JSON 형식으로 온다.
- [ ] 가공된 데이터 종류:
  - [ ] 7일간의 평균 값
  - [ ] 사용자 지정 시간의 평균 값
  - [ ] 예상 값
