### ISSUE TITLE
Sensor Api - 센서 설정 저장

### ISSUE THREAD

**Issue by kkh5535** [nhnacademy-aiot1-team3/roadmap#74]
- [ ] 권한 있는 사용자가 선택할 수 있도록 옵션을 저장한다.
- [ ] 센서 기능 타입, target value, 오차 범위, 시작 및 종료 날짜 시간을 지정할 수 있다.
- [ ] 적절한 데이터베이스를 사용하여 데이터를 관리해야 한다.
