### ISSUE TITLE
Chart Api - 맞춤 설정 기능

### ISSUE THREAD

**Issue by kkh5535** [nhnacademy-aiot1-team3/roadmap#82]
- [ ] 차트의 스타일, 색상, 축 레이블 등을 사용자가 맞춤 설정할 수 있는 기능이 필요한다.
- [ ] 사용자가 차트를 둘 수 있는 위치를 표시해주어야 한다.
- [ ] 사용자가 특정 장소의 데이터를 조회할 수 있도록 선택 목록을 줘야 한다.
